services:

  web:
    build: .
    volumes:
      - .:/var/www
    networks:
      - quattro

  nginx:
    image: nginx:latest
    networks:
      - quattro
    volumes:
      - .:/var/www
      - ./.container/nginx/default.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`quattro.localhost`)"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
      - "traefik.http.services.nginx.loadbalancer.server.scheme=http"


  traefik:
      image: traefik:latest
      command:
        - "--log.level=DEBUG"
        - "--api.insecure=true"
        - "--providers.docker=true"
        - "--providers.docker.exposedbydefault=false"
        - "--entrypoints.web.address=:80"
        - "--entrypoints.websecure.address=:443"
      ports:
        - "80:80"
        - "8080:8080"
      networks:
        - quattro
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

networks:
  quattro:
    external: false